<a href="https://colab.research.google.com/github/quantumseminar/textbook/blob/main/01libraries/libraries4_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 乱数
量子コンピュータや機械学習ではrandom numberをとてもよく利用する。全てツールで作れるので覚えておく。
まずはrandomを使う場合、

In [1]:
import random

In [3]:
# Random float:  0.0 <= x < 1.0
random.random()

0.48908526140627984

続けて行うと、違う値が出る。

In [13]:
random.random()

0.02096559877394022

0と1の間じゃなくて、0と10の間とかにしたい場合、10倍する。

In [12]:
random.random()*10

4.8290015131452515

範囲を指定する場合、

In [9]:
# Random float:  2.5 <= x <= 10.0
random.uniform(2.5, 10.0)

3.029362053011023

値を出さずに、文字を選ぶ場合、

In [11]:
random.choice(['win', 'lose', 'draw'])

'lose'

## numpyを利用する
numpyを利用する方が一般的かも。

In [14]:
import numpy as np

0と1の間の乱数

In [16]:
np.random.rand()

0.5909911749929717

配列を取り出す。下記は要素数が3個あるarrayとして乱数が作られます。

In [19]:
np.random.rand(3)

array([0.39470251, 0.46142023, 0.34757127])

配列を二次元にもできます

In [21]:
np.random.rand(2,2)

array([[0.17282531, 0.38025328],
       [0.19395582, 0.22214704]])

小数じゃなくて整数が欲しい場合はrandint()
引数が一つだと上限値

In [22]:
np.random.randint(5)

4

引数二つで範囲を指定

In [23]:
np.random.randint(0,5)

3

引数の三つ目には配列などを指定できる。
下は0から5の間の整数をランダムに要素数3の配列


In [26]:
np.random.randint(0,5,[3])

array([2, 1, 2])

## 乱数シード
乱数はシードを決めると再現できる。いつもバラバラなものばかりだと答えが合ってるのかわからなくなることがあるため、シードを固定することがある。

In [31]:
np.random.seed(1234)
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())

0.1915194503788923
0.6221087710398319
0.4377277390071145
0.7853585837137692
0.7799758081188035


In [33]:
np.random.seed(1234)
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())

0.1915194503788923
0.6221087710398319
0.4377277390071145
0.7853585837137692
0.7799758081188035


シードを固定すると毎回同じ番号が乱数として割り振られる。